# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
   
     
  deploy:
      machine:
          enabled: true
      working_directory: ~/repo
      environment:
        HEROKU_APP: "sleepy-refuge-55486"
      steps:
        - checkout
        - run:
            name: Setup Heroku
            command: bash .circleci/setup-heroku.sh

        - run:
            command: |
              git push heroku sequential-branch-filter:development
              heroku run rake db:migrate
              sleep 5 # sleep for 5 seconds to wait for dynos
              heroku restart
  workflows:
    version: 2
    deploy:
      jobs:
         - deploy:
             filters:
              branches:
                only: sequential-branch-filter
